name: sokolink
description: SokoLink ? marketplace B2B agroalimentaire RDC
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  file_picker: ^11.0.2
  crypto: ^3.0.6
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/sokolink-icon.png
  adaptive_icon_background: "#F3EDE4"
  adaptive_icon_foreground: assets/branding/sokolink-icon.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/branding/sokolink-icon.png
