export const DRC_PROVINCES = [
  'Kinshasa',
  'Kongo-Central',
  'Kwango',
  'Kwilu',
  'Mai-Ndombe',
  'Équateur',
  'Mongala',
  'Nord-Ubangi',
  'Sud-Ubangi',
  'Tshuapa',
  'Tshopo',
  'Bas-Uele',
  'Haut-Uele',
  'Ituri',
  'Nord-Kivu',
  'Sud-Kivu',
  'Maniema',
  'Haut-Katanga',
  'Lualaba',
  'Haut-Lomami',
  'Tanganyika',
  'Lomami',
  'Sankuru',
  'Kasaï',
  'Kasaï-Central',
  'Kasaï-Oriental',
] as const;

export const AGRO_CATEGORIES = [
  { slug: 'cereales-farines', nameFr: 'Céréales & farines' },
  { slug: 'tubercules', nameFr: 'Tubercules & dérivés' },
  { slug: 'huiles', nameFr: 'Huiles & oléagineux' },
  { slug: 'sucre', nameFr: 'Sucre & édulcorants' },
  { slug: 'cafe-cacao-the', nameFr: 'Café, cacao, thé' },
  { slug: 'proteines', nameFr: 'Protéines (viande, poisson, volaille)' },
  { slug: 'fruits-legumes', nameFr: 'Fruits, légumes & transformés' },
  { slug: 'boissons', nameFr: 'Boissons' },
  { slug: 'laitiers', nameFr: 'Produits laitiers' },
  { slug: 'emballages', nameFr: 'Emballages alimentaires' },
  { slug: 'autres', nameFr: 'Autres agro' },
] as const;
